# Generated by Django 3.0.7 on 2020-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukumbi', '0008_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_pic.jpg', upload_to='images'),
        ),
    ]
